---
# tasks file for apache
- name: install all packages
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ pkgs }}"

- name: enable and start services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ pkgs }}"

- name: firewall setup
  firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ rule }}"


- name: create info file from template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify:
    - Restart Httpd
